name: Test delete

on: delete
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: test the branch name
        run: |
          echo ${{ steps.extract_branch.outputs.branch }}
