# This is a basic workflow that is manually triggered

name: Import databricks notebooks

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: create


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:          
  Build:
    if: ${{ contains(github.ref, 'refs/heads/feature/') }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Databricks cli
      run: |
        python --version
        pip --version
        python -m pip install --upgrade pip
        pip --version
        pip install databricks-cli
        echo "Installed Databricks CLI"

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: 'databricks-int'
        path: ${{ github.repository }}
  
    - name: Import notebooks into databricks workspace
      run: |
        databricks --version
        echo "trying to import code into databricks.."
        #databricks workspace ls
        databricks workspace import_dir zoetis-comm/. /Users/ram.motaparthy@zoetis.com/databricks-test1 --overwrite --exclude-hidden-files

      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
